language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  fast_finish: true
  allow_failures:
    - php: 7

install:
    - travis_retry composer update $COMPOSER_OPTS --no-interaction --prefer-source

script:
  - if [[ "`phpenv version-name`" == "5.6" && $COMPOSER_OPTS == "" ]]; then phpunit --coverage-clover=coverage.clover; wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
  - if [[ "`phpenv version-name`" == "5.6" && $COMPOSER_OPTS != "" ]]; then phpunit; fi;
  - if [[ "`phpenv version-name`" != "5.6" ]]; then phpunit --exclude-group webhook; fi;
  - versions=(5.4 5.5 7.0) && if [[ ${versions[*]} =~ "`phpenv version-name`" ]]; then phpunit --group webhook; fi;

notifications:
  slack: xsolla:V74WgCQlV6kas6X9SNQKl5R1